May 17, 2025, 12:08:45 AM, Exception was thrown: Could not register item. Please try again.
se.kth.iv1350.pos.controller.OperationFailedException: Could not register item. Please try again.
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:88)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:62)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:37)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:84)
	... 2 more
May 17, 2025, 12:10:23 AM, Exception was thrown: Could not register item. Please try again.
se.kth.iv1350.pos.controller.OperationFailedException: Could not register item. Please try again.
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:88)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:62)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:37)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:84)
	... 2 more
May 17, 2025, 12:17:18 AM, Exception was thrown: Could not register item. Please try again.
se.kth.iv1350.pos.controller.OperationFailedException: Could not register item. Please try again.
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:88)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:62)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:37)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:84)
	... 2 more
May 31, 2025, 11:30:44 PM, Exception was thrown: Could not register item. Please try again.
se.kth.iv1350.pos.controller.OperationFailedException: Could not register item. Please try again.
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:89)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:68)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:85)
	... 2 more
Jun 1, 2025, 12:15:59 PM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:39)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Jun 1, 2025, 12:16:11 PM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:39)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Jun 1, 2025, 12:23:07 PM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:39)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Jun 1, 2025, 12:27:34 PM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:85)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Jun 2, 2025, 1:04:00 AM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:85)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Jun 2, 2025, 1:36:29 AM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:85)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Jun 2, 2025, 1:43:15 AM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:85)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
	at OutputTest.testMainMethodOutput(OutputTest.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Jun 2, 2025, 1:43:15 AM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:85)
	at OutputTest.testViewOutput(OutputTest.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
