May 17, 2025, 12:08:45 AM, Exception was thrown: Could not register item. Please try again.
se.kth.iv1350.pos.controller.OperationFailedException: Could not register item. Please try again.
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:88)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:62)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:37)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:84)
	... 2 more
May 17, 2025, 12:10:23 AM, Exception was thrown: Could not register item. Please try again.
se.kth.iv1350.pos.controller.OperationFailedException: Could not register item. Please try again.
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:88)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:62)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:37)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:84)
	... 2 more
May 17, 2025, 12:17:18 AM, Exception was thrown: Could not register item. Please try again.
se.kth.iv1350.pos.controller.OperationFailedException: Could not register item. Please try again.
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:88)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:62)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:37)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:84)
	... 2 more
May 31, 2025, 11:30:44 PM, Exception was thrown: Could not register item. Please try again.
se.kth.iv1350.pos.controller.OperationFailedException: Could not register item. Please try again.
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:89)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:68)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:85)
	... 2 more
Jun 1, 2025, 12:15:59 PM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:39)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Jun 1, 2025, 12:16:11 PM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:39)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Jun 1, 2025, 12:23:07 PM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:39)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
Jun 1, 2025, 12:27:34 PM, Exception was thrown: Could not connect to inventory database
se.kth.iv1350.pos.integration.DatabaseFailureException: Could not connect to inventory database
	at se.kth.iv1350.pos.integration.InventorySystem.getItem(InventorySystem.java:38)
	at se.kth.iv1350.pos.controller.Controller.enterItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:85)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:33)
